config/routes.rb
Rails.application.routes.draw do
  get 'open_weather_cities' => 'open_weather_cities#index'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :users
  resources :user_cities, only: [:index, :show, :destroy, :new]
  post '/user_cities/:open_weather_city_id' => 'user_cities#create'
  root 'user_cities#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/open_weather_city.rb
require 'open_weather'

class OpenWeatherCity < ApplicationRecord
  # APPID needs to be in an environment variable
  OPEN_WEATHER_OPTIONS = { units: "imperial", APPID: "fb1c9edf19acb8411170acba2a672f53"}
  has_many :user_cities

  validates_presence_of :city_id, :name, :country

  def self.city_search(name)
    if name
      where('name ILIKE ?', name.strip)
    end
  end

  def current_weather
    @current_weather ||= OpenWeather::Current.city_id(city_id, OPEN_WEATHER_OPTIONS)
  end

  def five_day_forecast
    options = OPEN_WEATHER_OPTIONS.merge(cnt: 5)
    OpenWeather::Forecast.city_id(city_id, options)["list"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :user_cities
end

app/models/user_city.rb
class UserCity < ApplicationRecord
  belongs_to :user
  belongs_to :open_weather_city

  validates_presence_of :user_id, :open_weather_city_id

  delegate :five_day_forecast, to: :open_weather_city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/open_weather_cities_controller.rb
class OpenWeatherCitiesController < ApplicationController
  before_action :require_login

  def index
    @open_weather_cities = OpenWeatherCity.city_search(params[:city_name])
  end
end

app/controllers/user_cities_controller.rb
class UserCitiesController < ApplicationController
  before_action :require_login
  before_action :set_user_city, only: [:show, :destroy]

  def index
    @user_cities = current_user.user_cities
  end

  def show
    @city     = WeatherPresenter.new(@user_city)
    @forecast = @user_city.five_day_forecast
  end

  def create
    @user_city = current_user.user_cities.build(user_city_params)
    respond_to do |format|
      if @user_city.save
        format.html { redirect_to @user_city, notice: 'User city was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @user_city.destroy
    respond_to do |format|
      format.html { redirect_to user_cities_url, notice: 'User city was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user_city
      @user_city = UserCity.find(params[:id])
    end

    def user_city_params
      params.permit(:user_id, :open_weather_city_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Weather
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/css/mdb.min.css", :rel => "stylesheet"}/

    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js", :type => "text/javascript"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js", :type => "text/javascript"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js", :type => "text/javascript"}
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/js/mdb.min.js", :type => "text/javascript"}

  %body
    = render 'shared/header'
    = render 'shared/flash_messages'
    = yield

app/views/open_weather_cities/_index.html.haml
%table.table
  %thead
    %tr
      %th City
      %th Country
      %th Open Weather ID
      %th Save as Favorite
  %tbody
    - @open_weather_cities.each do |city|
      %tr
        %td
          = city.name.titleize
        %td
          = city.country
        %td
          = city.city_id
        %td
          = link_to 'Save', user_city_path(city.id), method: :post, class: 'btn btn-sm btn-default'

app/views/open_weather_cities/index.js.erb
$("#city-list").html("<%= escape_javascript render("index") %>");

app/views/shared/_flash_messages.html.haml
%center#flash
  - flash.each do |key, value|
    %div{:class => "flash #{key}"}= value

app/views/shared/_header.html.haml
%header
  %nav.navbar.navbar-expand-lg.navbar-dark.default-color
    %a.navbar-brand{:href => root_path}
      %strong Weather
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        - if signed_in?
          %li.nav-item
            = link_to I18n.t("layouts.application.cities"), user_cities_path, class: 'nav-link'
          %li.nav-item
            = button_to I18n.t("layouts.application.sign_out"), sign_out_path, method: :delete, class: "nav-link btn btn-sm btn-elegant"

app/views/user_cities/index.html.haml
%br
.row
  .col-3
  .col-6
    %h1 Listing Saved Cities
    %table.table
      %thead
        %tr
          %th Location
          %th Current Temperature
          %th
          %th

      %tbody
        - @user_cities.each do |user_city|
          - weather = WeatherPresenter.new(user_city)
          %tr
            %td= weather.location
            %td= weather.current_temp
            %td= link_to 'Show', user_city
            %td= link_to 'Destroy', user_city, method: :delete, data: { confirm: 'Are you sure?' }

    %br

    = link_to 'New User city', new_user_city_path

app/views/user_cities/new.html.haml
%br
.row
  .col-4
    .card.mx-xl-5
      .card-body
        %h4 City Search
        .form-group
          %label City Name Search
          %input#city-search.form-control

  .col-8
    %h4 Matching Cities
    #city-list
      %p no cities found

:javascript
  $("#city-search").keyup(function() {
    var value = $(this).val();
    $.get("/open_weather_cities", { city_name: value });
    return false;
  });

app/views/user_cities/show.html.haml
%br
.row
  .col-4
    .card.mx-xl-5
      .card-body
        .row
          .col-12
            %h2
              = @city.location
          .col-6
            %p
              %b Temperature:
              = @city.current_temp
            %p
              %b Condition:
              = @city.current_condition
            %p
              %b Sunrise:
              = @city.sunrise
            %p
              %b Sunset:
              = @city.sunset
          .col-6
            = image_tag @city.icon_url, size: "80"
        = link_to 'Back', user_cities_path
  .col-6
    .card.mx-xl-5
      .card-body
        .row
          .col-12
            %h2 Five Day Forecast
          .col-12
            %table.table
              %thead
                %tr
                  %th Date
                  %th Average Temp
                  %th High
                  %th Low
                  %th Humidity
                  %th Condition
                  %th
              %tbody
                - @forecast.each do |day|
                  - daily_weather = ForecastPresenter.new(day)
                  %tr
                    %td
                      = daily_weather.date
                    %td
                      = daily_weather.temp
                    %td
                      = daily_weather.temp_max
                    %td
                      = daily_weather.temp_min
                    %td
                      = daily_weather.humidity
                    %td
                      = daily_weather.condition
                    %td
                      = image_tag daily_weather.icon_url, size: "35"

app/views/users/_form.html.haml
%p.h4.text-center.py-4 Sign Up
.form-group
  = form.label :email
  = form.text_field :email, type: 'email', class: 'form-control'
.form-group
  = form.label :password
  = form.password_field :password, class: 'form-control'

app/views/users/new.html.haml
%br
.row
  .col-3
  .col-6
    .card.mx-xl-5
      .card-body
        #clearance.sign-up
          = form_for @user do |form|
            = render partial: '/users/form', object: form
            .text-center.py-4
              = form.submit class: 'btn btn-default'
            %center.other-links
              = link_to t(".sign_in"), sign_in_path